[package]
name = "gitroot"
version = "0.2.1"
description = "A desktop git client that explains what it's doing, every time."
license = "MIT"
repository = "https://github.com/AbdelattyBadwy16/GitRoot"
homepage = "https://gitroot.pro/"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[[bin]]
name = "gitroot"
path = "src/main.rs"
